---
# tasks file for custom-idm-client

- name: Backup and remove sssd.conf
  block:
    - name: Check that files exists
      stat:
        path: /etc/sssd/sssd.conf
      register: sssd_result

    - name: Backup sssd.conf
      copy:
        remote_src: True
        src: "{{ sssd_result.stat.path }}"
        dest: "{{ sssd_result.stat.path }}.bak"
      when: sssd_result.stat.exists

    - name: Remove old sssd.conf
      file:
        path: "{{ sssd_result.stat.path }}"
        state: absent
      when: sssd_result.stat.exists

- name: Install iDM Client
  include_role:
    name: ipaclient 

# https://access.redhat.com/solutions/3242461
- name: KDC - fixing dns_lookup_kdc
  lineinfile:
    path: /etc/krb5.conf
    regexp: '\sdns_lookup_kdc'
    line: '  dns_lookup_kdc = true'
  notify:
  - restart sssd
  when: ipaclient_krb5_fix | bool

- name: KDC - fixing dns_lookup_realm
  lineinfile:
    path: /etc/krb5.conf
    regexp: '\sdns_lookup_realm'
    line: '  dns_lookup_realm = true'
  notify:
  - restart sssd
  when: ipaclient_krb5_fix | bool

- name: Setting default domain to login
  lineinfile:
    path: /etc/sssd/sssd.conf
    line: 'default_domain_suffix = {{ ad_domain }}'
    insertafter: '^\[sssd\]'
  notify: restart sssd
  when: ipa_client_set_default_domain | bool
