---
numberof_ipa_replicas: 1
numberof_ipa_clients: 1

ipa_realm: IDM.AD.TEST
ipa_domain: idm.ad.test
ipa_netbios: IDM
ipa_server_name: ipa
ipa_server_fqdn: '{{ ipa_server_name }}.{{ ipa_domain }}'
ipa_server_ip_address: 192.168.68.11
ipa_server_gateway: 192.168.68.254
ipa_client_krb5_fix: true
# Use Short Names to Resolve and Authenticate Users/Groups
ipaserver_use_short_names: true
ipa_client_set_default_domain: false

ad_realm: AD.TEST
ad_domain: ad.test
ad_netbios: AD
ad_server_name: dc1
ad_server_ip_address: 192.168.68.10
ad_server_gateway: 192.168.68.254
ad_admin_user: administrator@ad.test
ad_admin_password: IPApass1.
ad_safe_mode_password: IPApass1.

ipaadmin_password: IPApass1.
ipadm_password: IPApass1.
ipaserver_domain: '{{ ipa_domain }}'
ipaserver_realm: '{{ ipa_realm }}'
ipaserver_setup_dns: yes
ipareplica_setup_dns: yes
ipareplica_setup_ca: yes
ipaserver_auto_forwarders: yes
ipareplica_auto_forwarders: yes
#ipaserver_ipatrust_range_type: ipa-ad-trust-posix

ipaserver_setup_adtrust: yes
ipareplica_setup_adtrust: yes
ipaserver_ipatrust_range_type: ipa-ad-trust

ipaserver_no_hbac_allow: no
ipareplica_no_hbac_allow: no

timezone: GMT Standard Time
