---
ipa_realm: IDM.AD.TEST
ipa_domain: idm.ad.test
ipa_netbios: IDM
ipa_server_name: ipa
ipa_server_fqdn: '{{ ipa_server_name }}.{{ ipa_domain }}'
ipa_server_ip_address: 192.168.68.11
ipa_server_gateway: 192.168.68.254
ipa_replica_name: rep
ipa_replica_ip_address: 192.168.68.12
ipa_client_name: cli
ipa_client_ip_address: 192.168.68.13

ad_realm: AD.TEST
ad_domain: ad.test
ad_netbios: AD
ad_server_name: dc1
ad_server_ip_address: 192.168.68.10
ad_server_gateway: 192.168.68.254
ad_admin_user: administrator@ad.test
ad_admin_password: IPApass1.
ad_safe_mode_password: IPApass1.

ipaadmin_password: IPApass1.
ipadm_password: IPApass1.
ipaserver_domain: '{{ ipa_domain }}'
ipaserver_realm: '{{ ipa_realm }}'
ipaserver_setup_dns: yes
ipaserver_auto_forwarders: yes
ipaserver_setup_adtrust: yes