---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  collections:
    - freeipa.ansible_freeipa

  pre_tasks:
  - name: change /etc/hosts
    lineinfile:
      path: '/etc/hosts'
      regexp: '.*ipaserver.*'
      line: '192.168.9.16  ipaserver-1.idmb.local  ipaserver-1'
      backup: true

  roles:
  - role: ipaserver
    state: present
