---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  gather_facts: true
  collections:
    - freeipa.ansible_freeipa
  vars_files:
    - ../../default.config.yml
    - vars/main.yml
  pre_tasks:
  - name: Print variables for debugging
    debug:
      msg: "{{ domain }} {{ hostname }} {{inventory_hostname}}"
  - name: change /etc/hosts
    lineinfile:
      path: '/etc/hosts'
      regexp: '.*{{ hostname }}.*'
      line: '{{ ipaddress }}  {{ hostname }}.{{ domain}} {{hostname}}'
      backup: true
  roles:
  - role: ipaserver
    state: present
  tasks:
  - name: ensure presence of forwardzone
    ipadnsforwardzone:
      ipaadmin_password: '{{ ipaadmin_password }}'
      state: present
      name: '{{ ad_domain }}'
      forwarders:
        - ip_address: '{{ ad_server_ip_address }}'
      forwardpolicy: first
      skip_overlap_check: true
