---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  gather_facts: true
  collections:
    - freeipa.ansible_freeipa
  vars_files:
    - ../../default.config.yml
    - vars/main.yml
  pre_tasks:
  - name: Print variables for debugging
    debug:
      msg: "{{ domain }} {{ hostname }} {{inventory_hostname}}"
  - name: change /etc/hosts
    lineinfile:
      path: '/etc/hosts'
      regexp: '.*{{ hostname }}.*'
      line: '{{ ipaddress }}  {{ hostname }}.{{ domain}} {{hostname}}'
      backup: true
  roles:
  - role: ipaserver
    state: present
  tasks:
  - name: ensure presence of forwardzone
    ipadnsforwardzone:
      ipaadmin_password: '{{ ipaadmin_password }}'
      state: present
      name: '{{ ad_domain }}'
      forwarders:
        - ip_address: '{{ ad_server_ip_address }}'
      forwardpolicy: first
      skip_overlap_check: true

  - name: ensure the one-way trust present
    ipatrust:
      ipaadmin_password: '{{ ipaadmin_password }}'
      realm: "{{ ad_domain }}"
      admin: "{{ ad_admin_user }}"
      password: "{{ ad_admin_password }}"
      range_type: "{{ ipaserver_ipatrust_range_type }}"
      state: present
    when: ipaserver_setup_adtrust | bool

  - name: Create an external group and add members from a trust to it
    ipagroup:
      ipaadmin_password: '{{ ipaadmin_password }}'
      name: ad_domain_admins_external
      external: yes
      externalmember: "Domain Admins@{{ ad_domain }}"

  - name: Create internal group and add the external group as a member
    ipagroup:
      ipaadmin_password: '{{ ipaadmin_password }}'
      name: ad_domain_admins
      group: ad_domain_admins_external
  
  - name: Create HBAC rule for Domain Admins group
    ipahbacrule:
      ipaadmin_password: '{{ ipaadmin_password }}'
      name: ad_domain_admins_allow_all
      description: Allow Domain Admins to access any host from any host
      group: ad_domain_admins
      hostcat: all
      servicecat: all
      state: present

  - name: Add DNS records for ipa clients
    ipadnsrecord:
      ipaadmin_password: '{{ ipaadmin_password }}'
      zone_name: idm.ad.test
      name: rep
      a_rec:
        - 192.168.68.12