Vagrant.configure("2") do |config|
  config.vm.define "ipaserver-1.idmb.local" do |config|
    config.vm.box = "geerlingguy/centos8"
		config.vm.hostname = "ipaserver-1.idmb.local"
    config.vm.synced_folder '.', '/vagrant', disabled: true
		config.ssh.insert_key = false
    config.vm.network :private_network, ip: "192.168.9.16", gateway: "192.168.9.254"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "./ipaserver.yml"
        ansible.inventory_path = "./inventory"
        ansible.become = true
    end
  end
end