---
- name: Playbook to configure IPA clients
  become: true
  hosts: all
  gather_facts: true
  collections:
    - freeipa.ansible_freeipa
  vars_files:
    - ../../default.config.yml
    - vars/main.yml
  pre_tasks:
  - name: Ignore Auto DNS on NAT interface
    command: nmcli con mod enp0s3 ipv4.ignore-auto-dns yes
    notify: restart NetworkManager

  - name: Set a hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}.{{ domain }}"

  - name: Add IPv4 configuration
    community.general.nmcli:
      conn_name: System enp0s8
      type: ethernet
      dns4: "{{ ipa_server_ip_address }}"
      dns4_search: "{{ ipa_domain }}"
      state: present
    notify: restart NetworkManager

  roles:
  - role: ipaclient
    state: present
  tasks:
  # https://access.redhat.com/solutions/3242461
  - name: KDC - fixing dns_lookup_kdc
    lineinfile:
      path: /etc/krb5.conf
      regexp: '\sdns_lookup_kdc'
      line: '  dns_lookup_kdc = true'
    notify: restart sssd
    when: ipa_client_krb5_fix | bool

  - name: KDC - fixing dns_lookup_realm
    lineinfile:
      path: /etc/krb5.conf
      regexp: '\sdns_lookup_realm'
      line: '  dns_lookup_realm = true'
    notify: restart sssd
    when: ipa_client_krb5_fix | bool

  - name: Setting default domain to login
    lineinfile:
      path: /etc/sssd/sssd.conf
      line: 'default_domain_suffix = {{ ad_domain }}'
      insertafter: '^\[sssd\]'
    notify: restart sssd
    when: ipa_client_set_default_domain | bool

  - name: Ignore Auto DNS on NAT interface
    command: nmcli con mod enp0s3 ipv4.ignore-auto-dns yes
    notify: restart NetworkManager

  - name: Add IPv4 DNS server addresses
    community.general.nmcli:
      conn_name: System enp0s8
      type: ethernet
      dns4: " {{ ad_server_ip_address }}"
      state: present
    notify: restart NetworkManager

  - name: Add SSSD config
    template:
      src: templates/ipaclient.conf.j2
      dest: /etc/sssd/conf.d/ipaclient.conf

  handlers:
  - name: restart sssd
    service:
      name: sssd
      state: restarted

  - name: restart NetworkManager
    service:
      name: NetworkManager
      state: restarted