require 'yaml'
settings = YAML.load_file '../../default.config.yml'
fqdn = settings['ipa_client_name'] + "." + settings['ipa_domain']
Vagrant.configure("2") do |config|
  config.vm.define "cli" do |config|
    config.vm.box = "geerlingguy/centos8"
    config.vm.hostname = fqdn
    config.vm.synced_folder '.', '/vagrant', disabled: true
		config.ssh.insert_key = false
    config.vm.network :private_network, ip: settings['ipa_client_ip_address']

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "./playbook.yml"
        ansible.inventory_path = "./inventory"
        ansible.become = true
    end
  end
end