---
- name: Playbook to configure IPA replicas
  become: true
  hosts: all
  gather_facts: true
  collections:
    - freeipa.ansible_freeipa
  vars_files:
    - ../../default.config.yml
    - vars/main.yml
  pre_tasks:
  - name: Ignore Auto DNS on NAT interface
    command: nmcli con mod enp0s3 ipv4.ignore-auto-dns yes
    notify: restart NetworkManager

  - name: Set a hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}.{{ domain }}"

  - name: Add IPv4 configuration
    community.general.nmcli:
      conn_name: System enp0s8
      type: ethernet
      dns4: "{{ ipa_server_ip_address }}"
      dns4_search: "{{ ipa_domain }}"
      state: present
    notify: restart NetworkManager

  roles:
  - role: ipareplica
    state: present
  tasks:
  handlers:
  - name: restart NetworkManager
    service:
      name: NetworkManager
      state: restarted