require 'yaml'
settings = YAML.load_file '../../default.config.yml'
Vagrant.configure("2") do |config|
N = settings['numberof_ipa_replicas']
(1..N).each do |machine_id|

  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 2048
  end

  config.vm.define "replica#{machine_id}" do |machine|
    machine.vm.box = "geerlingguy/centos8"
    machine.vm.hostname = "replica#{machine_id}"
    machine.vm.network "private_network", ip: "192.168.68.#{11+machine_id}"
    machine.vm.synced_folder '.', '/vagrant', disabled: true
		machine.ssh.insert_key = false
    # Only execute once the Ansible provisioner,
    # when all the machines are up and ready.
    if machine_id == N
      machine.vm.provision :ansible do |ansible|
        # Disable default limit to connect to all the machines
        ansible.limit = "all"
        ansible.playbook = "playbook.yml"
      end
    end
  end
end
end
