galaxy_info:
  author: Gardar Thorsteinsson (gardart@gmail.com)
  description: Ansible role to install Red Hat iDM idm-client

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []

collections:
  - freeipa.ansible_freeipa
